# Generated by Django 4.2.27 on 2026-01-23 12:55

from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrismUser",
            fields=[
                (
                    "user_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("registration_id", models.IntegerField()),
                ("identity_key", models.TextField()),
                ("pre_keys_available", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prism User",
                "verbose_name_plural": "Prism Users",
                "db_table": "prism_users",
            },
        ),
        migrations.CreateModel(
            name="QueerCache",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=secrets.token_hex,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("ciphertext", models.TextField()),
                (
                    "icon_type",
                    models.CharField(
                        choices=[
                            ("heart", "Heart"),
                            ("coffee", "Coffee"),
                            ("history", "History"),
                            ("warning", "Warning"),
                            ("star", "Star"),
                        ],
                        default="heart",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "prism_caches",
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="prism_cache_latitud_b1bde6_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="prism_cache_expires_6b3cfa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=secrets.token_hex,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("nonprofit", "Non-Profit"),
                            ("healthcare", "Healthcare"),
                            ("community", "Community Center"),
                            ("housing", "Housing"),
                            ("business_food", "Business - Food"),
                            ("business_retail", "Business - Retail"),
                            ("business_service", "Business - Service"),
                            ("legal", "Legal Services"),
                            ("education", "Education"),
                            ("religious", "Religious"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("hours", models.CharField(blank=True, max_length=500)),
                ("tags", models.JSONField(default=list)),
                ("is_safe_space", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prism_organizations",
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="prism_organ_latitud_e5bc45_idx",
                    ),
                    models.Index(
                        fields=["org_type"], name="prism_organ_org_typ_d0f714_idx"
                    ),
                    models.Index(
                        fields=["is_active", "is_verified"],
                        name="prism_organ_is_acti_b628f0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MutualAidListing",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=secrets.token_hex,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creator_hash", models.CharField(max_length=64)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("offer", "Offering"), ("request", "Requesting")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("clothing", "Clothing"),
                            ("housing", "Housing"),
                            ("transport", "Transport"),
                            ("emotional", "Emotional Support"),
                            ("medical", "Medical"),
                            ("tech", "Tech Help"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("contact_cipher", models.TextField(blank=True)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "prism_mutual_aid",
                "indexes": [
                    models.Index(
                        fields=["listing_type", "is_fulfilled"],
                        name="prism_mutua_listing_a9b882_idx",
                    ),
                    models.Index(
                        fields=["category"], name="prism_mutua_categor_235e2c_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="prism_mutua_latitud_9fe69f_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="prism_mutua_expires_365987_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=secrets.token_hex,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("BUG", "Bug Report"),
                            ("FEAT", "Feature Request"),
                            ("SAFETY", "Safety Report"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ciphertext", models.TextField()),
                ("is_reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "prism_feedback",
                "indexes": [
                    models.Index(
                        fields=["feedback_type", "is_reviewed"],
                        name="prism_feedb_feedbac_e2569d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EncryptedMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=secrets.token_hex,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_hash", models.CharField(max_length=64)),
                ("recipient_hash", models.CharField(max_length=64)),
                ("ciphertext", models.TextField()),
                ("is_delivered", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "prism_messages",
                "indexes": [
                    models.Index(
                        fields=["recipient_hash", "is_delivered"],
                        name="prism_messa_recipie_89d0a9_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="prism_messa_expires_d51341_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Beacon",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=secrets.token_hex,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("trans_fem", "Trans Femme"),
                            ("trans_masc", "Trans Masc"),
                            ("nonbinary", "Non-Binary"),
                            ("bipoc_queer", "BIPOC Queer"),
                            ("queer_parents", "Queer Parents"),
                            ("newly_out", "Newly Out"),
                            ("queer_gamers", "Queer Gamers"),
                            ("queer_faith", "Queer & Faith"),
                            ("queer_sober", "Queer & Sober"),
                            ("general", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("broadcast_hash", models.CharField(max_length=64)),
                ("geohash", models.CharField(blank=True, max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "prism_beacons",
                "indexes": [
                    models.Index(
                        fields=["topic", "expires_at"],
                        name="prism_beaco_topic_a6f0d7_idx",
                    ),
                    models.Index(
                        fields=["geohash"], name="prism_beaco_geohash_cc5ec7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SignedPreKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_id", models.IntegerField()),
                ("public_key", models.TextField()),
                ("signature", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signed_pre_keys",
                        to="core.prismuser",
                    ),
                ),
            ],
            options={
                "db_table": "prism_signed_pre_keys",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="prism_signe_user_id_8eae05_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PreKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_id", models.IntegerField()),
                ("public_key", models.TextField()),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_keys",
                        to="core.prismuser",
                    ),
                ),
            ],
            options={
                "db_table": "prism_pre_keys",
                "indexes": [
                    models.Index(
                        fields=["user", "is_used"],
                        name="prism_pre_k_user_id_f6174a_idx",
                    )
                ],
                "unique_together": {("user", "key_id")},
            },
        ),
    ]
