# Generated by Django 6.0.2 on 2026-02-05 00:37

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="feedback",
            name="prism_feedb_feedbac_e2569d_idx",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="ciphertext",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="is_reviewed",
            new_name="email_sent",
        ),
        migrations.AddField(
            model_name="feedback",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="admin_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_hours",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_is_safe_space",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="feedback",
            name="org_website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="beacon",
            name="id",
            field=models.CharField(
                default=secrets.token_hex,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="encryptedmessage",
            name="id",
            field=models.CharField(
                default=secrets.token_hex,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(
                choices=[
                    ("bug", "Bug Report"),
                    ("feature", "Feature Request"),
                    ("org_submission", "Organization Submission"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.CharField(
                default=secrets.token_hex,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="mutualaidlisting",
            name="id",
            field=models.CharField(
                default=secrets.token_hex,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.CharField(
                default=secrets.token_hex,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="queercache",
            name="id",
            field=models.CharField(
                default=secrets.token_hex,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["feedback_type", "status"],
                name="prism_feedb_feedbac_e556b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["-created_at"], name="prism_feedb_created_df551f_idx"
            ),
        ),
    ]
