# Generated by Django 6.0.2 on 2026-02-05 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "location",
                    models.CharField(
                        help_text="City, State/Province, Country", max_length=255
                    ),
                ),
                (
                    "experience",
                    models.TextField(help_text="Experience with LGBTQ+ community work"),
                ),
                (
                    "motivation",
                    models.TextField(help_text="Why do you want to be an admin?"),
                ),
                (
                    "availability",
                    models.TextField(help_text="Time commitment you can offer"),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True,
                        help_text="Optional: References or community connections",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_sent", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "prism_admin_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TribePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tribe_id", models.CharField(max_length=100)),
                ("author_hash", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_by", models.CharField(blank=True, max_length=255)),
                ("deleted_reason", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "prism_tribe_posts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tribe_id", "-created_at"],
                        name="prism_tribe_tribe_i_272e68_idx",
                    ),
                    models.Index(
                        fields=["is_deleted"], name="prism_tribe_is_dele_4789f1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TribeReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("heart", "Heart"),
                            ("support", "Support"),
                            ("celebrate", "Celebrate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_hash", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="core.tribepost",
                    ),
                ),
            ],
            options={
                "db_table": "prism_tribe_reactions",
                "indexes": [
                    models.Index(
                        fields=["post", "reaction_type"],
                        name="prism_tribe_post_id_fd9fb0_idx",
                    )
                ],
                "unique_together": {("post", "user_hash", "reaction_type")},
            },
        ),
    ]
